### ISSUE TITLE
libssh2.gyp not found

### ISSUE THREAD

**Issue by raunsbaekdk** [JCMais/curl-for-windows#1] opened 2015-05-07 07:54 UTC
```
D:\NodeProjects\testingtesting>call cmd
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle rettigheder forbeholdes.

D:\NodeProjects\testingtesting>npm install node-libcurl@0.3.0
-
> node-libcurl@0.3.0 install D:\NodeProjects\testingtesting\node_modules\node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

File:  D:\NodeProjects\testingtesting\node_modules\node-libcurl\deps\curl-for-windows\libssh2.gyp  not found.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "node-libcurl@0.3.0"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.3.0 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.3.0 install script 'node tools/retrieve-win-deps && node tools/generate-stubs && n
ode-gyp rebuild'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\NodeProjects\testingtesting\npm-debug.log

D:\NodeProjects\testingtesting>
```

**Comment by raunsbaekdk** [comment] 2015-05-07 07:54
@JCMais Is this something you can check out?

**Comment by JCMais** [comment] 2015-05-07 18:40
Hi @raunsbaekdk, I cannot get to reproduce the issue you are having.

The module installs just fine here.

Which version of Git you have installed?

**Comment by raunsbaekdk** [comment] 2015-05-08 06:51
Hi @JCMais 

Git version 1.9.1.msysgit.1 from git-scm.com
Python 2.7 from the link recommended
Visual studio 2013 as well as old version of visual studio 2010

**Comment by Larvalis** [comment] 2015-05-08 09:50
Hey I tried to test it on a new computer, that had no developer programs installed. 
I installed:
- nodejs v0.12.2-x64
- Visual Studio Express 2013 with Update 4 for Windows Desktop
- Python 2.7.9
- Git-1.9.5-preview20150319
  in said order and tried to run the command `npm install node-libcurl`

What I got was about the same as the issue:

```
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle rettigheder forbeholdes.

C:\Users\Nomajin\Downloads\curltest>npm install node-libcurl
\
> node-libcurl@0.3.0 install C:\Users\Nomajin\Downloads\curltest\node_modules\
node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

File:  C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\deps\curl
-for-windows\libssh2.gyp  not found.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-libcurl"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.3.0 install: `node tools/retrieve-win-deps && node tools
/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.3.0 install script 'node tools/retrieve-wi
n-deps && node tools/generate-stubs && node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-g
yp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nomajin\Downloads\curltest\npm-debug.log

C:\Users\Nomajin\Downloads\curltest>
```

**Comment by JCMais** [comment] 2015-05-09 14:47
For some reason the submodule is not being initialized correctly, since the gyp file is not found.

As I cannot reproduce the issue, I can only speculate on it, I would try the following:
1. Make sure the cmd instance has administrator privileges
2. Run npm with --loglevel verbose and post the output again

**Comment by Larvalis** [comment] 2015-05-09 15:56
Btw. I am working together with raunsbaekdk.

I am personally new to github and node.js. I was just wondering if there were a connection with libssh2 @ f1cfa55 being the only folder without a clickable link, and the fact that the libssh2 is the thing that cannot be found? 

I did the test again running as administrator, and with --loglevel verbose:

```
C:\Users\Nomajin\Downloads\curltest>npm install node-libcurl --loglevel verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'node-libcurl',
npm verb cli   '--loglevel',
npm verb cli   'verbose' ]
npm info using npm@2.7.4
npm info using node@v0.12.2
npm verb node symlink C:\Program Files\nodejs\\node.exe
npm verb cache add spec node-libcurl
npm verb addNamed node-libcurl@*
npm verb addNameRange registry:https://registry.npmjs.org/node-libcurl not in flight; fetching
npm verb request uri https://registry.npmjs.org/node-libcurl
npm verb request no auth needed
npm info attempt registry request try #1 at 17:45:39
npm verb request id 2b24eb8b22b556fe
npm verb etag "2G023RDHGVSUWVUWXE6ZFF9SW"
npm http request GET https://registry.npmjs.org/node-libcurl
npm http 304 https://registry.npmjs.org/node-libcurl
npm verb etag https://registry.npmjs.org/node-libcurl from cache
npm verb get saving node-libcurl to C:\Users\Nomajin\AppData\Roaming\npm-cache\registry.npmjs.org\node-libcurl\.cache.json
npm verb addNamed node-libcurl@0.3.0
npm verb afterAdd C:\Users\Nomajin\AppData\Roaming\npm-cache\node-libcurl\0.3.0\package\package.json not in flight; writing
npm verb afterAdd C:\Users\Nomajin\AppData\Roaming\npm-cache\node-libcurl\0.3.0\package\package.json written
npm info install node-libcurl@0.3.0 into C:\Users\Nomajin\Downloads\curltest
npm info installOne node-libcurl@0.3.0
npm verb installOne of node-libcurl to C:\Users\Nomajin\Downloads\curltest not in flight; installing
npm verb lock using C:\Users\Nomajin\AppData\Roaming\npm-cache\_locks\node-libcurl-a6e5b4d0c5bf6e29.lock for C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
npm verb unbuild node_modules\node-libcurl
npm verb gentlyRm don't care about contents; nuking C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
npm verb tar unpack C:\Users\Nomajin\AppData\Roaming\npm-cache\node-libcurl\0.3.0\package.tgz
npm verb tar unpacking to C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
npm verb gentlyRm don't care about contents; nuking C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
npm info preinstall node-libcurl@0.3.0
npm verb cache add spec bindings@1.2.x
npm verb cache add spec nan@1.7.x
npm verb addNamed bindings@>=1.2.0 <1.3.0
npm verb addNameRange registry:https://registry.npmjs.org/bindings not in flight; fetching
npm verb addNamed nan@>=1.7.0 <1.8.0
npm verb addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb request uri https://registry.npmjs.org/bindings
npm verb request no auth needed
npm info attempt registry request try #1 at 17:45:40
npm verb etag "9RK4S5X0OXSOK2HUD8YR6PWNW"
npm http request GET https://registry.npmjs.org/bindings
npm verb request uri https://registry.npmjs.org/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 17:45:40
npm verb etag "D9X1WVB37H5NYMOI61FHEOYM0"
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to C:\Users\Nomajin\AppData\Roaming\npm-cache\registry.npmjs.org\nan\.cache.json
npm verb addNamed nan@1.7.0
npm verb afterAdd C:\Users\Nomajin\AppData\Roaming\npm-cache\nan\1.7.0\package\package.json not in flight; writing
npm verb afterAdd C:\Users\Nomajin\AppData\Roaming\npm-cache\nan\1.7.0\package\package.json written
npm http 304 https://registry.npmjs.org/bindings
npm verb etag https://registry.npmjs.org/bindings from cache
npm verb get saving bindings to C:\Users\Nomajin\AppData\Roaming\npm-cache\registry.npmjs.org\bindings\.cache.json
npm verb addNamed bindings@1.2.1
npm verb afterAdd C:\Users\Nomajin\AppData\Roaming\npm-cache\bindings\1.2.1\package\package.json not in flight; writing
npm verb afterAdd C:\Users\Nomajin\AppData\Roaming\npm-cache\bindings\1.2.1\package\package.json written
npm info install nan@1.7.0 into C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
npm info install bindings@1.2.1 into C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
npm info installOne nan@1.7.0
npm verb installOne of nan to C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl not in flight; installing
npm info installOne bindings@1.2.1
npm verb installOne of bindings to C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl not in flight; installing
npm verb lock using C:\Users\Nomajin\AppData\Roaming\npm-cache\_locks\nan-14d45049862dd516.lock for C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\nan
npm verb unbuild node_modules\node-libcurl\node_modules\nan
npm verb lock using C:\Users\Nomajin\AppData\Roaming\npm-cache\_locks\bindings-99eda48dad6160a0.lock for C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\bindings
npm verb unbuild node_modules\node-libcurl\node_modules\bindings
npm verb gentlyRm don't care about contents; nuking C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\nan
npm verb tar unpack C:\Users\Nomajin\AppData\Roaming\npm-cache\nan\1.7.0\package.tgz
npm verb tar unpacking to C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\bindings
npm verb tar unpack C:\Users\Nomajin\AppData\Roaming\npm-cache\bindings\1.2.1\package.tgz
npm verb tar unpacking to C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\bindings
npm verb gentlyRm don't care about contents; nuking C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\bindings
npm info preinstall bindings@1.2.1
npm verb about to build C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\bindings
npm info build C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\bindings
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   'C:\\Users\\Nomajin\\Downloads\\curltest\\node_modules\\node-libcurl\\node_modules' ]
npm info linkStuff bindings@1.2.1
npm verb linkBins bindings@1.2.1
npm verb linkMans bindings@1.2.1
npm verb rebuildBundles bindings@1.2.1
npm info install bindings@1.2.1
npm info postinstall bindings@1.2.1
npm verb unlock done using C:\Users\Nomajin\AppData\Roaming\npm-cache\_locks\bindings-99eda48dad6160a0.lock for C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\bindings
npm info preinstall nan@1.7.0
npm verb about to build C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\nan
npm info build C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\nan
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   'C:\\Users\\Nomajin\\Downloads\\curltest\\node_modules\\node-libcurl\\node_modules' ]
npm info linkStuff nan@1.7.0
npm verb linkBins nan@1.7.0
npm verb linkMans nan@1.7.0
npm verb rebuildBundles nan@1.7.0
npm info install nan@1.7.0
npm info postinstall nan@1.7.0
npm verb unlock done using C:\Users\Nomajin\AppData\Roaming\npm-cache\_locks\nan-14d45049862dd516.lock for C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\node_modules\nan
npm verb about to build C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
npm info build C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   'C:\\Users\\Nomajin\\Downloads\\curltest\\node_modules' ]
npm info linkStuff node-libcurl@0.3.0
npm verb linkBins node-libcurl@0.3.0
npm verb linkMans node-libcurl@0.3.0
npm verb rebuildBundles node-libcurl@0.3.0
npm verb rebuildBundles [ 'bindings', 'nan' ]
npm info install node-libcurl@0.3.0

> node-libcurl@0.3.0 install C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

File:  C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl\deps\curl-for-windows\libssh2.gyp  not found.
npm verb unsafe-perm in lifecycle true
npm info node-libcurl@0.3.0 Failed to exec install script
npm verb unlock done using C:\Users\Nomajin\AppData\Roaming\npm-cache\_locks\node-libcurl-a6e5b4d0c5bf6e29.lock for C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl
npm verb stack Error: node-libcurl@0.3.0 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1015:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm verb pkgid node-libcurl@0.3.0
npm verb cwd C:\Users\Nomajin\Downloads\curltest
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-libcurl" "--loglevel" "verbose"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.3.0 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.3.0 install script 'node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules\node-libcurl
npm info preuninstall node-libcurl@0.3.0
npm info uninstall node-libcurl@0.3.0
npm verb unbuild rmStuff node-libcurl@0.3.0 from C:\Users\Nomajin\Downloads\curltest\node_modules
npm info postuninstall node-libcurl@0.3.0
npm verb gentlyRm don't care about contents; nuking C:\Users\Nomajin\Downloads\curltest\node_modules\node-libcurl

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nomajin\Downloads\curltest\npm-debug.log

C:\Users\Nomajin\Downloads\curltest>
```

**Comment by Larvalis** [comment] 2015-05-18 10:22
I tried again and got a different error. Even through I did no changes, it now comes with the error:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [D:\NodeProjects\curltest\node_modules\node-libcurl\build\deps\curl-for-windows\libcurl.vcxproj]
```

I should have the Visual Studio 2010 version installed, at least the Web developer part. But I later installed the 2013 version.

The full log is:

```
D:\NodeProjects\curltest>npm install
\
> node-libcurl@0.3.0 install D:\NodeProjects\curltest\node_modules\node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild


D:\NodeProjects\curltest\node_modules\node-libcurl>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..
\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build t
ools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please in
stall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting t
he Project menu or right-click the solution, and then selecting "Upgrade Solution...". [D:\NodeProjects\curltest\node
_modules\node-libcurl\build\deps\curl-for-windows\libcurl.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build t
ools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please in
stall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting t
he Project menu or right-click the solution, and then selecting "Upgrade Solution...". [D:\NodeProjects\curltest\node
_modules\node-libcurl\build\deps\curl-for-windows\libssh2.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build t
ools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please in
stall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting t
he Project menu or right-click the solution, and then selecting "Upgrade Solution...". [D:\NodeProjects\curltest\node
_modules\node-libcurl\build\deps\curl-for-windows\openssl.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build t
ools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please in
stall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting t
he Project menu or right-click the solution, and then selecting "Upgrade Solution...". [D:\NodeProjects\curltest\node
_modules\node-libcurl\build\deps\curl-for-windows\zlib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
67:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd D:\NodeProjects\curltest\node_modules\node-libcurl
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! node-libcurl@0.3.0 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.3.0 install script 'node tools/retrieve-win-deps && node tools/generate-stubs && n
ode-gyp rebuild'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\NodeProjects\curltest\npm-debug.log

D:\NodeProjects\curltest>
```

**Comment by Larvalis** [comment] 2015-05-18 10:31
I was wondering if there is a special part of the 2010 express that is needed?
As the installer give you a choice between 4 istallations:
- Visual C# 2010 Express
- Visual basic 2010 Express
- Visual C++ 2010 Express
- Visual Web Developer 2010 Express

**Comment by JCMais** [comment] 2015-05-18 13:22
You should install Visual C++ 2010 Express.

Also, I'm using Visual Studio 2012, so I don't see the issue being VS2013.

You can try the following:

Download the repo: https://github.com/JCMais/node-libcurl/archive/master.zip
Extract it (preferably inside a top level directory, like D:\node-libcurl), and run the following: `node tools\retrieve-win-deps.js`, this command should retrieve the windows dependencies in the folder deps\curl-for-windows.

Doing that you are not installing the module, it's just a way to see what is the problem.

**Comment by Larvalis** [comment] 2015-05-18 14:20
I downloaded the repo, delete the folder "curl-for-windows" in deps and ran the command `node tools\retrieve-win-deps.js` It then downloaded all the files without problems.

**Comment by Larvalis** [comment] 2015-05-18 14:42
After installing Visual C++ 2010 Express, I tried to install it the standard way again, and got the same error about `build tools for Visual Studio 2010` again.

**Comment by JCMais** [comment] 2015-05-18 14:55
I would recommend removing visual studio 2010 completely. First because I didn't tested to build using it, and second because it's really old. I'm going to download VS 2013 to try to compile using it, to eliminate any possible problem in regard to the compiler you were using.

But for now, go to the folder you extracted the project, and ran the command I said above, and run the following: `npm install --msvs_version=2013`. Paste the result here.

**Comment by Larvalis** [comment] 2015-05-18 15:13
I used the command `npm install node-libcurl --msvs_version=2013` as I was running into a few problems using project folder where I need it installed, I did it in another folder, and moved the installed files to the right project..
It seems to have been installed successfully, however I have not tested yet if it works.

The last lines of output I got was:

```
  Generating code
  Finished generating code
  node-libcurl.vcxproj -> D:\NodeProjects\Curltest\node_modules\node-libcurl\build\Release\\node-libcurl.node
node-libcurl@0.3.0 node_modules\node-libcurl
├── bindings@1.2.1
└── nan@1.7.0
```

I had only set my cmd to list 2000 lines, and it ran out of space, so I cannot see the top. There is more than 100 conversion warnings looking like this:

```
..\..\..\deps\curl-for-windows\openssl\openssl\engines\e_chil.c(831): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [D:\NodeProjects\Curltest\node_modules\node-libcurl\build\deps\curl-for-windows\openssl.vcxproj]
```

Also from __int64 to long, __int64 to unsigned char, size_t to int ect.

**Comment by Larvalis** [comment] 2015-05-18 15:16
It does seem to work, the code we made on Mac, is running fine without errors here on windows now.

**Comment by JCMais** [comment] 2015-05-18 15:25
> There is more than 100 conversion warnings looking like this:

You can ignore those warnings, it's because you are compiling to a x64 architecture.

Closing this, since looks like the issue was fixed, if the problem reappears, reopen it. Or if it's another issue related specifically to the node-libcurl package, open a new one on https://github.com/JCMais/node-libcurl/issues.

:+1:

**Closed as completed** 2015-05-18 15:28 UTC

**Comment by Larvalis** [comment] 2015-05-18 15:29
Thank you for your help
